version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          command: go test -parallel 4
          working_directory: ~/project/jobpostings
workflows:
  version: 2
  test_code:
    jobs:
      - test
