version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: export GO111MODULE=on
      - run: cd jobpostings
      - run: go mod download
      - run: go mod tidy
      - run: go mod verify
workflows:
  version: 2
  build_example:
    jobs:
      - build