version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: cd jobpostings
      - run: GO111MODULE=on go mod download
      - run: GO111MODULE=on go mod verify
      - run: GO111MODULE=on go test -run HashiCorp
workflows:
  version: 2
  build_example:
    jobs:
      - build