name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      total_jobs: ${{ steps.test.outputs.total_jobs }}
    steps:
    - uses: actions/checkout@v1
    - id: test
      name: Test
      working-directory: ./jobpostings
      run: |
        go test -timeout 1h github.com/job-hunter-toolkit/job-hunter-toolkit/jobpostings -run TestGetAllJobPostings -v | tee test.txt
        TOTAL_JOBS=$(cat test.txt | grep "Total job posings" | awk -F ': ' '{print $4}')
        echo "::set-output name=total_jobs::$TOTAL_JOBS"
  report_total_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Report Total Jobs
      run: echo ${{needs.test.outputs.total_jobs}}
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: go get -u -v github.com/job-hunter-toolkit/job-hunter-toolkit
