name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      working-directory: ./jobpostings
      run: go test -timeout 2h -parallel 4 .
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: go get -u github.com/job-hunter-toolkit/job-hunter-toolkit
