name: Track Jobs

on:
  schedule:
  - cron: "0 9 * * *"

jobs:
  job_sources:
    runs-on: ubuntu-latest
    outputs:
      job_sources: ${{ steps.job_sources.outputs.job_sources }}
    steps:
    - uses: actions/checkout@v2
    - id: job_sources
      name: Job Sources
      run: |
        JOB_SOURCES=$(go run main.go job-sources | wc -l)
        echo "::set-output name=job_sources::$JOB_SOURCES"
  test:
    runs-on: ubuntu-latest
    outputs:
      total_jobs: ${{ steps.test.outputs.total_jobs }}
    steps:
    - uses: actions/checkout@v2
    - id: test
      name: Test
      working-directory: ./jobpostings
      run: |
        go test -timeout 5h github.com/job-hunter-toolkit/job-hunter-toolkit/jobpostings -run TestGetAllJobPostings -v | tee test.txt
        TOTAL_JOBS=$(cat test.txt | grep "Total job posings" | awk -F ': ' '{print $3}')
        echo "::set-output name=total_jobs::$TOTAL_JOBS"
  report_total_jobs:
    runs-on: ubuntu-latest
    needs: [ test, job_sources ]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Report Total Jobs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DATE=$(date "+%m/%d/%y")
        TOTAL_JOBS=${{needs.test.outputs.total_jobs}}
        JOB_SOURCES=${{needs.job_sources.outputs.job_sources}}
        echo "Total jobs on $DATE was $TOTAL_JOBS"
        echo "Total sources on $DATE was $JOB_SOURCES"

        # if the number wasn't reported for the day, add it to the record
        if ! grep --silent $DATE jobs_record.txt; then
          sudo apt-get install -y gnuplot
          git config user.name "Job Hunter Toolkit Bot"
          git config user.email "job-hunter-toolkit@users.noreply.github.com"
          git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
          echo "$DATE $TOTAL_JOBS $JOB_SOURCES" >> jobs_record.txt
          gnuplot jobs_record.gnuplot
          git add .
          git commit -m "update jobs_record.txt for $DATE with $TOTAL_JOBS total jobs from $JOB_SOURCES sources"
          git push origin HEAD:master
        fi
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: go get -u -v github.com/job-hunter-toolkit/job-hunter-toolkit
